"use strict";

const actions = {
	"READY": require("./READY"),
	"MESSAGE_CREATE": require("./MESSAGE_CREATE"),
	"MESSAGE_DELETE": require("./MESSAGE_DELETE"),
	"MESSAGE_UPDATE": require("./MESSAGE_UPDATE"),
	"INTERACTION_CREATE": require("./INTERACTION_CREATE"),
	"CHANNEL_CREATE": require("./CHANNEL_CREATE"),
	"CHANNEL_UPDATE": require("./CHANNEL_UPDATE"),
	"CHANNEL_DELETE": require("./CHANNEL_DELETE"),
	"GUILD_UPDATE": require("./GUILD_UPDATE"),
	"GUILD_CREATE": require("./GUILD_CREATE"),
	"GUILD_DELETE": require("./GUILD_DELETE"),
	"GUILD_MEMBER_ADD": require("./GUILD_MEMBER_ADD"),
	"GUILD_MEMBER_REMOVE": require("./GUILD_MEMBER_REMOVE"),
	"GUILD_MEMBER_UPDATE": require("./GUILD_MEMBER_UPDATE"),
	"GUILD_ROLE_CREATE": require("./GUILD_ROLE_CREATE"),
	"GUILD_ROLE_UPDATE": require("./GUILD_ROLE_UPDATE"),
	"GUILD_ROLE_DELETE": require("./GUILD_ROLE_DELETE")
};
module.exports = actions;